config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'store#home'
  resources :products
  resources :line_items
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout   # /cart/checkout
    end
  end

  resources :orders, only: [:index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    found_item = line_items.find_by(product: product)

    if found_item
      found_item.quantity += 1
    else
      found_item = line_items.build(product: product)
    end

    found_item
  end

  def empty?
    line_items.count == 0
  end

  def total_price
    line_items.sum(&:total_price)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  belongs_to :user
  has_many :order_items

  before_create :create_serial

  aasm column: 'status', no_direct_assignment: true do
    state :pending, initial: true
    state :paid, :delivered, :cancelled, :refunded

    event :pay do
      transitions from: :pending, to: :paid

      after_commit do
        puts "發送簡訊!"
        # 簡訊服務
      end
    end

    event :deliver do
      transitions from: :paid, to: :delivered
    end

    event :cancel do
      transitions from: [:pending, :paid, :delivered], to: :cancelled
    end

    event :refund do
      transitions from: [:cancelled, :paid, :delivered], to: :refunded
    end
  end

  private
    def create_serial
      self.serial = serial_generator(id) # dont do that
    end

    def serial_generator(id)
      Time.now.strftime("%Y%m%d#{id.to_s.rjust(8, "0")}")
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord

  def abbr_title
    title.split(" ").map { |word| word.first }.join("")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CurrentCart

  helper_method :current_cart
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include BraintreeUtils
  before_action :authenticate_user!

  def show
  end

  def destroy
    empty_cart!
    redirect_to root_path, notice: "購物車已清空！"
  end

  def checkout
    @order = Order.new
    @token = gateway.client_token.generate
  end
end

app/controllers/concerns/braintree_utils.rb
module BraintreeUtils
  def gateway
    Braintree::Gateway.new(
      environment: :sandbox,
      merchant_id: ENV["braintree_merchant_id"],
      public_key: ENV["braintree_public_key"],
      private_key: ENV["braintree_private_key"]
    )
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  private
  def find_cart
    @cart = Cart.find(session[:cart9527])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart9527] = @cart.id
  end

  def current_cart
    find_cart
    @cart
  end

  def empty_cart!
    Cart.find_by(id: session[:cart9527]).destroy
    session[:cart9527] = nil
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :find_cart, only: [:create]

  def create
    if user_signed_in?
      product = Product.find(params[:product_id])
      line_item = @cart.add_product(product)

      notice = line_item.save ? "已成功加入購物車" : "加入購物車發生錯誤"
      redirect_to root_path, notice: notice
    else
      redirect_to root_path, notice: "請先登入會員"
    end
  end

  private
    def line_items_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  include BraintreeUtils
  include CurrentCart

  def create
    # 建立訂單
    order = current_user.orders.new(order_params)

    # 從購物車把東西拿出來 -> order item
    current_cart.line_items.each do |item|
      order.order_items.new(
        product: item.product,
        quantity: item.quantity
      )
    end

    if order.save
      # 刷卡（交易）

      result = gateway.transaction.sale(
        amount: current_cart.total_price,
        payment_method_nonce: params[:nonce],
        options: {
          submit_for_settlement: true
        }
      )

      if result.success?
        # 清購物車
        empty_cart!
        order.pay!
        redirect_to root_path, notice: "感謝大爺"
      else
        redirect_to root_path, notice: "刷卡發生錯誤"
      end

    else
      redirect_to root_path, notice: order.errors.full_messages
    end


    # 離開 -> 首頁

    # render html: params
  end

  private
    def order_params
      params.require(:order).permit(:receiver, :tel, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def home
    @products = Product.page(params[:page]).per(8)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_helper.rb
module ProductHelper
  def product_img(product)
    color1, color2  = img_color(product)

    image_tag "https://fakeimg.pl/350x200/#{color1},#{color2}/#{color2},#{color1}/?text=#{product.abbr_title}&font=lobster"
  end

  private
    def img_color(product)
      color1 = (product.title.to_i(36) % 255).to_s.rjust(3, "0")
      color2 = (product.title.to_i(24) % 255).to_s.rjust(3, "0")
      return color1, color2
    end
end

app/views/carts/_cart.html.erb
<ul class="my-2">
  <% current_cart.line_items.each do |item| %>
    <li class="cart-item-list">
      <div class="w-36">
        <%= product_img(item.product) %>
      </div>
      <div>
        <%= item.product.title %>
      </div>
      <div>
        NTD <%= number_to_currency item.product.price %>
      </div>
      <div>
        <%= item.quantity %>
      </div>
    </li>
  <% end %>
  </ul>

app/views/carts/checkout.html.erb
<h1 class="text-xl">結帳</h1>

<%= render "cart" %>

<%= form_for(@order) do |f| %>
  <div data-controller="payment" data-payment-token-value="<%= @token %>"></div>

  <%= f.text_field :receiver, class: "input", placeholder: "收件人姓名" %>
  <%= f.text_field :tel, class: "input", placeholder: "連絡電話" %>
  <%= f.text_field :address, class: "input", placeholder: "收件地址" %>
  <%= f.submit "送出訂單", class: "btn-action" %>
<% end %>

app/views/carts/show.html.erb
<h1 class="h1">購物車</h1>

<% if current_cart.empty? %>
  <p class="text-lg my-4">
    目前空空的，回<%= link_to "上一頁", root_path, class: "underline" %>挑一些東西吧！
  </p>
<% else %>
  <ul class="my-2">
  <% current_cart.line_items.each do |item| %>
    <li class="cart-item-list">
      <div class="w-36">
        <%= product_img(item.product) %>
      </div>
      <div>
        <%= item.product.title %>
      </div>
      <div>
        NTD <%= number_to_currency item.product.price %>
      </div>
      <div>
        <%= item.quantity %>
      </div>
    </li>
  <% end %>
  </ul>
<% end %>

<section class="flex mt-4">
<%= link_to "商品列表", root_path, class: "bg-blue-500 px-4 py-2 text-white text-lg" %>
<%= link_to "清空購物車", cart_path, method: :delete, data: {confirm: "確認清空購物車?!"}, class: "bg-green-500 px-4 py-2 text-white text-lg" unless current_cart.empty? %>
<%= link_to "結帳！", checkout_cart_path, class: "bg-red-500 px-4 py-2 text-white text-lg" unless current_cart.empty? %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingMallV3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto my-2">
      <%= render "shared/navbar" %>
      <%= render "shared/flash" if notice %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flex h-screen">
  <h1 class="m-auto font-thin text-8xl">Hello World</h1>
</div>

app/views/shared/_flash.html.erb
<div class="flash">
  <%= notice %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <ul>
    <% if user_signed_in? %>
      <li>
        <span class="mr-2"><%= current_user.email %></span>
        <%= link_to "登出", destroy_user_session_path, method: :delete %>
      </li>
      <li>
        <%= link_to "購物車 (#{current_cart.line_items.count})", cart_path %>
      </li>
    <% else %>
      <li>
        <%= link_to "註冊", new_user_registration_path %>
        <%= link_to "登入", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/store/home.html.erb
<h1 class="h1">賺很大商店</h1>

<section class="products">
  <% @products.each do |product| %>
  <div class="product">
    <%= product_img(product) %>
    <p class="title"><%= product.title %></p>
    <p class="price">NTD <%= number_to_currency product.price %></p>
    <p class="description"><%= product.description %></p>
    <%= link_to "加到購物車", line_items_path(product_id: product.id), method: 'post', class: 'addToCartBtn' %>
  </div>
  <% end %>
</section>

<%= paginate @products %>